import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import { SocketDataProvider } from "@/providers/SocketContext";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased border border-white`}
      >
        <SocketDataProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SocketDataProvider>
        <div className="relative  z-10">
          <ToastContainer
            position="bottom-left"
            autoClose={2000}
            theme="dark"
          />
        </div>
      </body>
    </html>
  );
}
